### ISSUE TITLE
Add lazy loading to images!

### ISSUE THREAD

**Issue by mayanksha** [ECell-IITK/esummit18#4]
The present page load times really feel sluggish. For a first time visitor, the page takes almost 5-6 seconds to render even on a good internet connection, owing to the `window.onload` handler to fire and remove the loading screen (that flipping box). 

To fasten up the site, you can add lazy loading to images so that images can be fetched on the fly. 
You can take help from this commit https://github.com/ECell-IITK/ecell/commit/74f0685c2fb749c3f19b700ee139bc52b6685b0f

**Comment by anujms1999** [comment]
https://github.com/ECell-IITK/esummit18/pull/5

**Comment by ubarsaiyan** [comment]
Closed by #5
